env:
  branch: ${{ github.head_ref || github.ref_name }}
  ENV: production
  APP: example-app
  REGISTRY: ${YOUR_AWS_ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/example-app
name: 🧱 Production CI/CD Pipeline
on:
  push:
    branches:
      - "main"
jobs:
  Deploy_Production:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.4.2
        with:
          ref: ${{ env.branch }}
        
      - name: Configure AWS credentials
        id: aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        id: setup
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}:${{ github.sha }}
          repository: ${{ env.REGISTRY }}

      - name: Store Docker Image Tag in SSM
        id: store-ssm
        run: |
          aws ssm put-parameter --name "/${{ env.ENV }}/dollar-store-kids-metadata-server/config/imageTag" --value "${{ github.sha }}" --type "String" --overwrite

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.1.0'

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/environments/production

      - name: Terraform Plan
        run: terraform plan
        working-directory: infrastructure/environments/production

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infrastructure/environments/production
